#! /bin/sh
### BEGIN INIT INFO
# Provides:          wlan1ap
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set wlan1 as AP if exist.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here


case "$1" in
  start)
    log_begin_msg "Starting wlan1ap service."
# do something
    # Confirm wlan1 by checking result of ifconfig wlan1
    ifconfig wlan1
    echo $?
    if [ $? -eq 0 ] ; then
      sudo /etc/init.d/dnsmasq start
      sudo /etc/init.d/hostapd start
      sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
      wsshd &
    fi

    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping the wlan1ap serice."

    # do something to kill the service or cleanup or nothing
    sudo /etc/init.d/dnsmasq stop
    sudo /etc/init.d/hostapd stop
    pkill -f wsshd

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/wlan1ap {start|stop}"
    exit 1
    ;;
esac
